### PR TITLE
Release - set version to 1.23.0-rc2

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/11238

### CODE REVIEW

**Review by clebs — DISMISSED** [review]

**Comment by adamwalach** [comment]
I think we can't release rc1 because it fails on kyma integration tests:
```
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  41s                default-scheduler  Successfully assigned kyma-system/oct-tp-test-922-dex-connection-0 to cli-integration-test-a47c1a9d
  Normal   Pulling    25s (x2 over 40s)  kubelet            Pulling image "tutum/curl:alpine"
  Warning  Failed     24s (x2 over 38s)  kubelet            Failed to pull image "tutum/curl:alpine": rpc error: code = Unknown desc = Error response from daemon: pull access denied for tutum/curl, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     24s (x2 over 38s)  kubelet            Error: ErrImagePull
  Normal   BackOff    10s (x2 over 38s)  kubelet            Back-off pulling image "tutum/curl:alpine"
  Warning  Failed     10s (x2 over 38s)  kubelet            Error: ImagePullBackOff
  ```
This issue is fixed on [Kyma 1.23.0-rc2](https://github.com/kyma-project/kyma/pull/11346/files#diff-65c86d0747e244e439ccc1dfce0295903ad45e4e0da11bdaa6fd6dd8db577073L26)
  I'd say - lets skip rc1 for kyma-cli and go directly with rc2, @clebs WDYF?

**Review by clebs — APPROVED** [review]

**Pull request merged**
