### PR TITLE
Support minikube docker driver

### PR DESCRIPTION
**Pull request by DimitarPetrov**
Add docker driver in supported minikube VM drivers.

### CODE REVIEW

**Comment by suleymanakbas91** [comment]
Thanks for the PR @DimitarPetrov! The only missing part is the documentation change. Can you please run `make docs` and then commit the changed md file?

**Review by suleymanakbas91 — APPROVED** [review]

**Review by bszwarc — APPROVED** [review]

**Comment by suleymanakbas91** [comment]
Many thanks for the contribution @DimitarPetrov!

**Pull request merged**
