### PR TITLE
Check error message for docker-env

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Review by clebs — APPROVED** [review]
LGTM!

Only one remark, I understand that this behaviour is only for OS = Linux and driver = none combination, would it make sense to validate that the scenario is indeed what is expected before running this?

**Comment by Ressetkk** [comment]
The problem occurs only when driver=none is used, because minikube's `minikube docker-env` is not compatible when this driver is in use. That fails the command prematurely.

**Comment by clebs** [comment]
Yes I do understand the issue, my question was only if it would make sense to check that the OS is Linux when we get into this branch. Because as I understand, with other OSes it will not work.

But anyways, the PR is approved, so if you think that checking the OS is not necessary it is also ready to merge.

**Comment by Ressetkk** [comment]
Based on the [minikube docs](https://minikube.sigs.k8s.io/docs/drivers/) the driver `none` is supported only by Linux so running it on the platform other than Linux will return minikube error:
```
$ kyma provision minikube --vm-driver=none 
- Requirements verified
  Preparing Minikube using vm-driver 'none'
? Do you want to remove the existing Minikube cluster? Type [Y/n]: y
- Minikube status verified
- Minikube config initialized
X Create Minikube instance
Error: Executing the 'minikube start --memory 8192 --cpus 4 --extra-config=apiserver.authorization-mode=RBAC --extra-config=apiserver.cors-allowed-origins='http://*' --extra-config=apiserver.enable-admission-plugins=DefaultStorageClass,LimitRanger,MutatingAdmissionWebhook,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,ValidatingAdmissionWebhook --kubernetes-version=v1.16.3 --vm-driver none --disk-size 30g -b kubeadm' command with output '* minikube v1.12.3 on Darwin 10.15.6
X The driver 'none' is not supported on darwin
' and error message 'exit status 69' failed
```

**Pull request merged**
