### PR TITLE
Release 2.9 cherry-pick: adapt to recent changes in operators

### PR DESCRIPTION
**Pull request by Tomasz-Smelcerz-SAP**
**Description**

Cherry-pick of "remove module-manager 'operator' folder" into the release 2.9 branch
Changes proposed in this pull request:

- remove module-manager 'operator' folder

**Related issue(s)**
#1459

### CODE REVIEW

**Review by jeremyharisch — APPROVED** [review]

**Review by jeremyharisch — COMMENTED** [review]
When I try to deploy Kyma on a new k3d Cluster, created with Kyma CLI, I get the following 
```
./bin/kyma-darwin alpha deploy
- Kustomize ready
- Lifecycle Manager deployed
- Module Manager deployed
- Modules deployed
X Failed to deploy Kyma CR
Error: Kyma.operator.kyma-project.io "default-kyma" is invalid: spec.channel: Unsupported value: "stable": supported values: "alpha", "fast", "regular"
```

Please adapt https://github.com/kyma-project/cli/blob/8b83fa4643f2c26b4544d148d1e34ab5d3f107cf/internal/deploy/kyma.go#L46
to `regualr`

**Comment by Tomasz-Smelcerz-SAP** [comment]
@jeremyharisch I have added two more commits from main. Now the changeset is consistent with main up to the `3edc5b0 refactor: remove module-manager 'operator' folder (#1459)` commit.

**Comment by jeremyharisch** [comment]
> @jeremyharisch I have added two more commits from main. Now the changeset is consistent with main up to the `3edc5b0 refactor: remove module-manager 'operator' folder (#1459)` commit.
> 
> The question is, should we also include the other changes from main?

@Tomasz-Smelcerz-SAP I think that should be suffcient! Tested it and works 👍🏻

**Comment by jeremyharisch** [comment]
@grego952 @mmitoraj could one of you have a look?

**Review by grego952 — APPROVED** [review]

**Pull request merged**
