### PR TITLE
Support the `customRuntimeImage` field for the `config.yaml` and the `run function` method

### PR DESCRIPTION
**Pull request by pPrecel**
**Description**

Changes proposed in this pull request:

- add the `custom-runtime-image` flag to the `run function` command
- support new field `customRuntimeImage` in the `config.yaml`

**Related issue(s)**

- https://github.com/kyma-project/kyma/issues/13555
- https://github.com/kyma-project/kyma/pull/13708

### CODE REVIEW

**Comment by moelsayed** [comment]
Looks good, thank you.

**Review by moelsayed — APPROVED** [review]
/lgtm

**Review by Cortey — APPROVED** [review]

**Review by grego952 — APPROVED** [review]

**Pull request merged**
