### PR TITLE
Consistent flag naming

### PR DESCRIPTION
**Pull request by shorim**
**Description**

Changes proposed in this pull request:

- avoid using camelCase naming for flags in order to have consistency in the naming style
- `noWait`, `tlsCert` , `tlsKey` , `FallbackLevel` and `hypervVirtualSwitch` flags are changed to `no-wait`, `tls-cert`, `tls-key`, `fallback-level` and `hyperv-virtual-switch` respectively.

**Related issue(s)**

#431

### CODE REVIEW

**Review by clebs — APPROVED** [review]
LGTM!

As follow up, I would ask you to check if there are any changes needed in the kyma docs, specially under: https://kyma-project.io/docs/#installation-installation

**Review by suleymanakbas91 — COMMENTED** [review]
In addition to docs, we need to adapt test-infra scripts as well. Otherwise, as soon as we create a new stable binary, they will start failing. Also, this should be documented in the release changelog as it is breaking.

**Comment by shorim** [comment]
@clebs I have checked the kyma docs and only found that only `tlsCert` and `tlsKey` were used there. Here is the PR: https://github.com/kyma-project/kyma/pull/9988

**Comment by shorim** [comment]
@suleymanakbas91 I have searched the test-infra repo for the usage of any of the changed 5 flags. Only found `tlsCert` and `tlsKey` used in multiple scripts. Here is the PR: https://github.com/kyma-project/test-infra/pull/2966

**Review by alexandra-simeonova — APPROVED** [review]

**Pull request merged**
