### PR TITLE
Bump 2.1.2

### PR DESCRIPTION
**Pull request by ruanxin**
**Description**

Changes proposed in this pull request:
update version to 2.1.2

backporting of changes:
https://github.com/kyma-project/cli/pull/1224
https://github.com/kyma-project/cli/pull/1223
https://github.com/kyma-project/cli/pull/1226
https://github.com/kyma-project/cli/pull/1229
https://github.com/kyma-project/cli/pull/1230
https://github.com/kyma-project/cli/pull/1233
https://github.com/kyma-project/cli/pull/1234
https://github.com/kyma-project/cli/pull/1236

**Related issue(s)**

### CODE REVIEW

**Review by a-thaler — CHANGES_REQUESTED** [review]
Based on main branch which will bring all changes from main into the release, please fix

**Review by NHingerl — APPROVED** [review]

**Pull request merged**
