### PR TITLE
Silence deprecation warnings

### PR DESCRIPTION
**Pull request by elchead**
**Description**
Changes from https://github.com/kyma-project/hydroform/pull/315 must be removed with https://github.com/kyma-project/hydroform/pull/328 before merging this PR.

This PR silences the deprecation warning on `install` and `alpha deploy`.

### CODE REVIEW

**Comment by JeremyHarisch** [comment]
Some deprecation warning are still printed out. Please check again.
```
- Deploying pre-requisites finished successfully
- Component 'kiali' deployed
- Component 'tracing' deployed
2021/06/28 08:38:23 Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml.
- Component 'monitoring' deployed
- Component 'api-gateway' deployed
\ Deploying Kyma W0628 08:39:10.943761    7975 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
| Deploying Kyma W0628 08:39:10.985585    7975 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
/ Deploying Kyma W0628 08:39:11.271139    7975 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
- Deploying Kyma W0628 08:39:11.419632    7975 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
- Component 'service-catalog' deployed
- Component 'logging' deployed
- Component 'service-catalog-addons' deployed
[...]
```

How did I test it? 

1. Check out this PR
2. `make build darwin`
3. `./bin/kyma-darwin alpha provision k3s`
4. `./bin/kyma-darwin alpha deploy`

**Comment by JeremyHarisch** [comment]
When testing I get the following results:
TestCase 1 - install kyma using kyma install:
1. `./bin/kyma-darwin alpha provision k3s`
2. `./bin/kyma-darwin install kyma`
Result:
```
Cluster type determined
  Installing Kyma in version 'main-da9a13cf'
- Preparations done
  Failed to get the installation status. Will retry later...
  Failed to get the installation status. Will retry later...
- Waiting for installation to start
- install component cluster-essentials
- install component testing
- install component istio
- install component xip-patch
- install component dex
- install component ory
- install component api-gateway
- install component rafter
[...]
```
Works

TestCase 2 - Install Kyma using alpha deploy:
1. `./bin/kyma-darwin alpha provision k3s`
2. `./bin/kyma-darwin alpha deploy`
Result:
```
No previous Kyma version found
- Kyma downloaded into workspace folder
| Deploying pre-requisites W0701 16:38:14.360425   41426 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
/ Deploying pre-requisites W0701 16:38:16.274997   41426 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
- Component 'cluster-essentials' deployed
- Component 'istio' deployed
[...]
```
Deprecation warnings still exists, please adapt in such way that those are also not shown in `alpha deploy`

**Comment by elchead** [comment]
image
tested

**Review by JeremyHarisch — APPROVED** [review]

**Comment by JeremyHarisch** [comment]
This PR silences the deprecation warning while `kyma install` and `kyma alpha deploy`.
At first it was tried to silence the `alpha deploy` inside hydroform with this PR https://github.com/kyma-project/hydroform/pull/315. Now, every deprecation warning is silenced only in CLI, thus changes in hydroform could be removed with https://github.com/kyma-project/hydroform/pull/328.

**Pull request merged**
