### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by adamwalach**
**Description**

Changes proposed in this pull request:

- updated documentation

**Related issue(s)**

### CODE REVIEW

**Comment by a-thaler** [comment]
Was there no prow job complaining that you missed it?

**Comment by adamwalach** [comment]
There should be, @skhalash checks why it wasn't triggered.
I will not merge this PR until we bring it back.

**Review by skhalash — APPROVED** [review]

**Review by klaudiagrz — APPROVED** [review]

**Pull request merged**
