### PR TITLE
Bump hydroform function package

### PR DESCRIPTION
**Pull request by dbadura**
**Description**

Changes proposed in this pull request:

- use newer hydroform

**Related issue(s)**
[](https://github.com/kyma-project/kyma/issues/11155)

### CODE REVIEW

**Comment by pPrecel** [comment]
I have a small problem because when I'm trying to apply function workspace with a few labels then the output function is created without any additional labels :(

```yaml
name: function-gifted-michal5
namespace: default
runtime: nodejs14
labels:
  any-label: any-value
  something-else: else-value
source:
    sourceType: inline
    sourcePath: /tmp/funcs
```

**Review by pPrecel — APPROVED** [review]

**Review by clebs — APPROVED** [review]

**Pull request merged**
