### PR TITLE
Add terraform debug option and abstract provision template

### PR DESCRIPTION
**Pull request by elchead**
**Description**

Changes proposed in this pull request:

- use the verbose flag to enable the output of terraform errors and logs
- remove duplicate code in cmd.run() by defining a template

**Related issue(s)**
#882

### CODE REVIEW

**Comment by elchead** [comment]
Please review the Hydroform PR first to pass the CI test

**Comment by elchead** [comment]
@clebs the tests passed now

**Review by clebs — APPROVED** [review]

**Pull request merged**
